name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Sync labels
      uses: facelessuser/wildcard-labeler-action@feature/code
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
