name: labels

on:
  push:
    branches:
      - 'master'

jobs:
  label-sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Sync labels
      uses: facelessuser/label-mgr-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        mode: 'delete'
